/**
 * Pinned markdown output, generated by `.tmp/gen-markdown-fixtures.mts` from the implementation that
 * lived in `apps/web/lib/markdown.ts` before the move into @klndr/core. The parser and the HTML
 * renderer must keep reproducing this byte for byte; regenerate deliberately, never to make a test pass.
 */

export type MarkdownCase = { name: string; source: string; html: string };
export type ToggleCase = { name: string; source: string; line: number; output: string };

export const markdownCases: MarkdownCase[] = [
  {
    "name": "empty input",
    "source": "",
    "html": ""
  },
  {
    "name": "blank lines only",
    "source": "\n\n   \n\t\n",
    "html": ""
  },
  {
    "name": "single paragraph",
    "source": "Just one line.",
    "html": "<p>Just one line.</p>"
  },
  {
    "name": "two paragraphs",
    "source": "First para\nstill first\n\nSecond para",
    "html": "<p>First para<br>still first</p><p>Second para</p>"
  },
  {
    "name": "soft break inside a paragraph",
    "source": "a\nb",
    "html": "<p>a<br>b</p>"
  },
  {
    "name": "heading levels",
    "source": "# One\n\n## Two\n\n###### Six",
    "html": "<h1>One</h1><h2>Two</h2><h6>Six</h6>"
  },
  {
    "name": "seven hashes is not a heading",
    "source": "####### Seven",
    "html": "<p>####### Seven</p>"
  },
  {
    "name": "hash without a space is not a heading",
    "source": "#nospace",
    "html": "<p>#nospace</p>"
  },
  {
    "name": "indented hash is not a heading",
    "source": "   # indented",
    "html": "<p>   # indented</p>"
  },
  {
    "name": "trailing hashes",
    "source": "## Closed ##",
    "html": "<h2>Closed ##</h2>"
  },
  {
    "name": "horizontal rules",
    "source": "---\n\n***\n\n___\n\n- - -\n\n* * *\n\n_ _ _",
    "html": "<hr><hr><hr><hr><hr><hr>"
  },
  {
    "name": "blockquote",
    "source": "> quoted\n> second line\n\nplain",
    "html": "<blockquote>quoted<br>second line</blockquote><p>plain</p>"
  },
  {
    "name": "empty blockquote",
    "source": ">",
    "html": "<blockquote></blockquote>"
  },
  {
    "name": "blockquote with emphasis",
    "source": "> **bold** quote",
    "html": "<blockquote><strong>bold</strong> quote</blockquote>"
  },
  {
    "name": "fenced code",
    "source": "```\nconst a = 1 < 2 && \"x\";\n```",
    "html": "<pre><code>const a = 1 &lt; 2 &amp;&amp; &quot;x&quot;;</code></pre>"
  },
  {
    "name": "fenced code with a language",
    "source": "```js\nlet x = 1;\n```",
    "html": "<pre><code>let x = 1;</code></pre>"
  },
  {
    "name": "unterminated fence",
    "source": "```\nunclosed",
    "html": "<pre><code>unclosed</code></pre>"
  },
  {
    "name": "fence keeps blank lines",
    "source": "```\na\n\nb\n```",
    "html": "<pre><code>a\n\nb</code></pre>"
  },
  {
    "name": "fence with html",
    "source": "```\n<b>&</b>\n```",
    "html": "<pre><code>&lt;b&gt;&amp;&lt;/b&gt;</code></pre>"
  },
  {
    "name": "unordered list",
    "source": "- a\n- b",
    "html": "<ul><li>a</li><li>b</li></ul>"
  },
  {
    "name": "list markers change kind",
    "source": "- a\n- b\n\n* c\n+ d",
    "html": "<ul><li>a</li><li>b</li></ul><ul><li>c</li><li>d</li></ul>"
  },
  {
    "name": "ordered list",
    "source": "1. a\n2. b",
    "html": "<ol><li>a</li><li>b</li></ol>"
  },
  {
    "name": "ordered list with parens",
    "source": "1) a\n2) b",
    "html": "<ol><li>a</li><li>b</li></ol>"
  },
  {
    "name": "ordered list starting at five",
    "source": "5. a\n6. b",
    "html": "<ol><li>a</li><li>b</li></ol>"
  },
  {
    "name": "nested list by spaces",
    "source": "- a\n  - b\n    - c\n      - d\n        - e",
    "html": "<ul><li>a</li><li style=\"margin-left:1.25rem\">b</li><li style=\"margin-left:2.5rem\">c</li><li style=\"margin-left:3.75rem\">d</li><li style=\"margin-left:3.75rem\">e</li></ul>"
  },
  {
    "name": "nested list by tab",
    "source": "- a\n\t- b",
    "html": "<ul><li>a</li><li style=\"margin-left:1.25rem\">b</li></ul>"
  },
  {
    "name": "mixed marker kinds are separate lists",
    "source": "- a\n1. b",
    "html": "<ul><li>a</li></ul><ol><li>b</li></ol>"
  },
  {
    "name": "task list",
    "source": "- [ ] todo\n- [x] done\n- [X] also done\n- [] not a task",
    "html": "<ul><li class=\"task\"><input type=\"checkbox\" data-line=\"0\"><span>todo</span></li><li class=\"task done\"><input type=\"checkbox\" data-line=\"1\" checked><span>done</span></li><li class=\"task done\"><input type=\"checkbox\" data-line=\"2\" checked><span>also done</span></li><li>[] not a task</li></ul>"
  },
  {
    "name": "task in an ordered list",
    "source": "1. [ ] first\n2. [x] second",
    "html": "<ol><li class=\"task\"><input type=\"checkbox\" data-line=\"0\"><span>first</span></li><li class=\"task done\"><input type=\"checkbox\" data-line=\"1\" checked><span>second</span></li></ol>"
  },
  {
    "name": "task list after a paragraph",
    "source": "Intro line\n\n- [ ] one\n- [x] two",
    "html": "<p>Intro line</p><ul><li class=\"task\"><input type=\"checkbox\" data-line=\"2\"><span>one</span></li><li class=\"task done\"><input type=\"checkbox\" data-line=\"3\" checked><span>two</span></li></ul>"
  },
  {
    "name": "list item line numbers",
    "source": "para\n\n- [ ] a\n- [x] b\n\nmore\n\n- [ ] c",
    "html": "<p>para</p><ul><li class=\"task\"><input type=\"checkbox\" data-line=\"2\"><span>a</span></li><li class=\"task done\"><input type=\"checkbox\" data-line=\"3\" checked><span>b</span></li></ul><p>more</p><ul><li class=\"task\"><input type=\"checkbox\" data-line=\"7\"><span>c</span></li></ul>"
  },
  {
    "name": "emphasis",
    "source": "**bold** __also bold__ *em* _also em_ ~~strike~~",
    "html": "<p><strong>bold</strong> <strong>also bold</strong> <em>em</em> <em>also em</em> <del>strike</del></p>"
  },
  {
    "name": "emphasis at boundaries",
    "source": "a*b*c and a_b_c and snake_case_here",
    "html": "<p>a*b*c and a_b_c and snake_case_here</p>"
  },
  {
    "name": "nested emphasis",
    "source": "**a *b* c**",
    "html": "<p>**a <em>b</em> c**</p>"
  },
  {
    "name": "unclosed emphasis",
    "source": "a *star and a _underscore",
    "html": "<p>a *star and a _underscore</p>"
  },
  {
    "name": "lone markers",
    "source": "* _ ** __ ~~",
    "html": "<ul><li>_ ** __ ~~</li></ul>"
  },
  {
    "name": "inline code",
    "source": "use `npm run dev` here",
    "html": "<p>use <code>npm run dev</code> here</p>"
  },
  {
    "name": "code span protects markers",
    "source": "`code with *stars* and _underscores_`",
    "html": "<p><code>code with *stars* and _underscores_</code></p>"
  },
  {
    "name": "emphasis spanning a code span",
    "source": "**`code`**",
    "html": "<p><strong><code>code</code></strong></p>"
  },
  {
    "name": "link with a label",
    "source": "[label](https://example.com/path?a=1&b=2)",
    "html": "<p><a href=\"https://example.com/path?a=1&amp;b=2\" target=\"_blank\" rel=\"noopener noreferrer\">label</a></p>"
  },
  {
    "name": "unsupported link scheme",
    "source": "[bad](javascript:alert(1))",
    "html": "<p>[bad](javascript:alert(1))</p>"
  },
  {
    "name": "mailto link",
    "source": "[mail me](mailto:me@example.com)",
    "html": "<p><a href=\"mailto:me@example.com\" target=\"_blank\" rel=\"noopener noreferrer\">mail me</a></p>"
  },
  {
    "name": "bare autolink",
    "source": "see https://example.com/x right there",
    "html": "<p>see <a href=\"https://example.com/x\" target=\"_blank\" rel=\"noopener noreferrer\">https://example.com/x</a> right there</p>"
  },
  {
    "name": "autolink in parentheses",
    "source": "(https://example.com)",
    "html": "<p>(<a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">https://example.com</a>)</p>"
  },
  {
    "name": "autolink at the start",
    "source": "https://example.com is the site",
    "html": "<p><a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">https://example.com</a> is the site</p>"
  },
  {
    "name": "link label with emphasis",
    "source": "[*x*](https://e.com)",
    "html": "<p><a href=\"https://e.com\" target=\"_blank\" rel=\"noopener noreferrer\"><em>x</em></a></p>"
  },
  {
    "name": "emphasis inside a bare url",
    "source": "https://e.com/a*b*c",
    "html": "<p><a href=\"https://e.com/a*b*c\" target=\"_blank\" rel=\"noopener noreferrer\">https://e.com/a*b*c</a></p>"
  },
  {
    "name": "html is escaped",
    "source": "<script>alert('x') & \"y\"</script>",
    "html": "<p>&lt;script&gt;alert(&#39;x&#39;) &amp; &quot;y&quot;&lt;/script&gt;</p>"
  },
  {
    "name": "quotes and ampersands",
    "source": "He said \"hi\" & left <fast>.",
    "html": "<p>He said &quot;hi&quot; &amp; left &lt;fast&gt;.</p>"
  },
  {
    "name": "crlf document",
    "source": "a\r\nb\r\n\r\n- c\r\n- [x] d\r\n\r\n> e\r\n",
    "html": "<p>a<br>b</p><ul><li>c</li><li class=\"task done\"><input type=\"checkbox\" data-line=\"4\" checked><span>d</span></li></ul><blockquote>e</blockquote>"
  },
  {
    "name": "lone carriage return",
    "source": "a\rb",
    "html": "<p>a<br>b</p>"
  },
  {
    "name": "nul placeholder text",
    "source": "`c` and \u00000\u0000 plus \u0000",
    "html": "<p><code>c</code> and <code>c</code> plus \u0000</p>"
  },
  {
    "name": "everything at once",
    "source": "# Title\n\nIntro **bold** with `code`.\n\n> quote\n\n- [ ] task one\n  - nested\n- [x] task two\n\n```\nfence\n```\n\n---\n\nclosing https://example.com",
    "html": "<h1>Title</h1><p>Intro <strong>bold</strong> with <code>code</code>.</p><blockquote>quote</blockquote><ul><li class=\"task\"><input type=\"checkbox\" data-line=\"6\"><span>task one</span></li><li style=\"margin-left:1.25rem\">nested</li><li class=\"task done\"><input type=\"checkbox\" data-line=\"8\" checked><span>task two</span></li></ul><pre><code>fence</code></pre><hr><p>closing <a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">https://example.com</a></p>"
  }
];

export const toggleTaskLineCases: ToggleCase[] = [
  {
    "name": "empty source",
    "source": "",
    "line": 0,
    "output": ""
  },
  {
    "name": "unchecked to checked",
    "source": "- [ ] a\n- [x] b",
    "line": 0,
    "output": "- [x] a\n- [x] b"
  },
  {
    "name": "checked to unchecked",
    "source": "- [ ] a\n- [x] b",
    "line": 1,
    "output": "- [ ] a\n- [ ] b"
  },
  {
    "name": "uppercase x",
    "source": "- [X] a",
    "line": 0,
    "output": "- [ ] a"
  },
  {
    "name": "line without a checkbox",
    "source": "- plain",
    "line": 0,
    "output": "- plain"
  },
  {
    "name": "out of range line",
    "source": "- [ ] a",
    "line": 5,
    "output": "- [ ] a"
  },
  {
    "name": "negative line",
    "source": "- [ ] a",
    "line": -1,
    "output": "- [ ] a"
  },
  {
    "name": "checkbox mid paragraph",
    "source": "text [ ] more",
    "line": 0,
    "output": "text [x] more"
  },
  {
    "name": "crlf source",
    "source": "- [ ] a\r\n- [ ] b",
    "line": 1,
    "output": "- [ ] a\r\n- [x] b"
  },
  {
    "name": "only the first checkbox on the line",
    "source": "- [ ] a [ ] b",
    "line": 0,
    "output": "- [x] a [ ] b"
  }
];
